/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas.Bioskop;

/**
 *
 * @author Asus
 */
public class GUI_Tiket extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Tiket
     */
    public GUI_Tiket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama_Film = new javax.swing.JTextField();
        txtDurasi_Film = new javax.swing.JTextField();
        txtAsal_Film = new javax.swing.JTextField();
        radiobtnSiang = new javax.swing.JRadioButton();
        radiobtnMalam = new javax.swing.JRadioButton();
        txtHarga = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        memoTiket = new javax.swing.JTextArea();
        btn_Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Data Tiket Bioskop");

        jLabel2.setText("Nama Film");

        jLabel3.setText("Durasi Film");

        jLabel4.setText("Asal Film");

        jLabel5.setText("Waktu Tayang");

        jLabel6.setText("Harga");

        txtNama_Film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNama_FilmActionPerformed(evt);
            }
        });

        txtDurasi_Film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurasi_FilmActionPerformed(evt);
            }
        });

        txtAsal_Film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAsal_FilmActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiobtnSiang);
        radiobtnSiang.setText("13.00");

        buttonGroup1.add(radiobtnMalam);
        radiobtnMalam.setText("18.00");
        radiobtnMalam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnMalamActionPerformed(evt);
            }
        });

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        memoTiket.setColumns(20);
        memoTiket.setRows(5);
        jScrollPane1.setViewportView(memoTiket);

        btn_Close.setText("Close");
        btn_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(btnCetak)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Close))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiobtnMalam)
                                    .addComponent(radiobtnSiang)
                                    .addComponent(txtAsal_Film, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDurasi_Film, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNama_Film, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNama_Film, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtDurasi_Film, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtAsal_Film, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(radiobtnSiang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radiobtnMalam))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetak)
                    .addComponent(btn_Close))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNama_FilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNama_FilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNama_FilmActionPerformed

    private void txtDurasi_FilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurasi_FilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasi_FilmActionPerformed

    private void txtAsal_FilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsal_FilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsal_FilmActionPerformed

    private void radiobtnMalamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnMalamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobtnMalamActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btn_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CloseActionPerformed
        // TODO add your handling code here:
        //exit
        dispose(); //fungsi untuk close app
    }//GEN-LAST:event_btn_CloseActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        
        memoTiket.setText(""); //setting memo agar kosong
        Film flm = new Film(); //mendeklarasikan object baru flm dalam class Film
        flm.dataNamaFilm(txtNama_Film.getText()); //mengambil data nama film dalam txtNama_Film
        flm.dataDurasi(txtDurasi_Film.getText()); //mengambil data durasi film dalam txtDurasi_Film
        flm.dataAsalFilm(txtAsal_Film.getText()); //mengambil data asal film dalam txtAsal_Film
        String WktTyng=""; //mendeklarasikam variabel baru dengan String
        if (radiobtnSiang.isSelected()){ //jika radio button Siang ditekan
             flm.dataTayang(radiobtnSiang.getText()); //mengambil data tayang Siang hari
        }else{ //jika tidak
             flm.dataTayang(radiobtnMalam.getText()); //mengambil data tayang Malam hari
        }
        flm.dataHarga(txtHarga.getText()); ////mengambil data Harga dalam txtHarga
        
        memoTiket.append("Data Tiket Bioskop\n"); //menampilkan teks pada memo/textArea
        memoTiket.append("======================\n"); //menampilkan teks pada memo/textArea
        memoTiket.append("Nama Film : " + flm.cetakNama_Film() + "\n"); //menampilkan teks pada memo/textArea
        memoTiket.append("Durasi Film : " + flm.cetakDurasi() + "\n"); //menampilkan teks pada memo/textArea
        memoTiket.append("Asal Film : " + flm.cetakAsal_Film() + "\n"); //menampilkan teks pada memo/textArea
        memoTiket.append("Waktu Tayang Film : " + flm.cetakTayang() + "\n"); //menampilkan teks pada memo/textArea
        memoTiket.append("Harga Tiket Film : " + flm.cetakHarga() + "\n"); //menampilkan teks pada memo/textArea
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Tiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btn_Close;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea memoTiket;
    private javax.swing.JRadioButton radiobtnMalam;
    private javax.swing.JRadioButton radiobtnSiang;
    private javax.swing.JTextField txtAsal_Film;
    private javax.swing.JTextField txtDurasi_Film;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama_Film;
    // End of variables declaration//GEN-END:variables
}
